apiVersion: aws.caas.upbound.io/v1alpha1
kind: XIRSA
metadata:
  name: haarchri-spaces-01-flux-kustomize-controller
spec:
  parameters:
    deletionPolicy: Delete
    id: haarchri-spaces-01
    condition: StringEquals
    policyDocument: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Action": [
                      "kms:Decrypt",
                      "kms:DescribeKey"
                  ],
                  "Effect": "Allow",
                  "Resource": "*"
              }
          ]
      }
    serviceAccount:
      name: kustomize-controller
      namespace: flux-system
