apiVersion: aws.caas.upbound.io/v1alpha1
kind: XIRSA
metadata:
  name: haarchri-spaces-01-flux-kustomize-controller
spec:
  parameters:
    deletionPolicy: Delete
    oidcArn: arn:aws:iam::609897127049:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/02053DCA0262B21293420E0A3B39E81B
    oidcHost: oidc.eks.eu-central-1.amazonaws.com/id/02053DCA0262B21293420E0A3B39E81B
    condition: StringEquals
    policyDocument: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Action": [
                      "kms:Decrypt",
                      "kms:DescribeKey"
                  ],
                  "Effect": "Allow",
                  "Resource": "*"
              }
          ]
      }
    serviceAccount:
      name: kustomize-controller
      namespace: flux-system
