apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - irsa-aws-load-balancer-controller.yaml
  - irsa-external-dns.yaml
  - irsa-flux-kustomize-controller.yaml
