apiVersion: aws.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: haarchri-spaces-01
  namespace: default
spec:
  parameters:
    id: haarchri-spaces-01
    region: eu-central-1
    version: "1.27"
    iam:
      roleArn: arn:aws:iam::609897127049:role/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
    nodes:
      count: 3
      instanceType: m5.xlarge
    gitops:
      url: https://github.com/haarchri/spaces-gitops
  writeConnectionSecretToRef:
    name: haarchri-spaces-01-kubeconfig
