apiVersion: v1
kind: ConfigMap
metadata:
  name: postbuild-settings
  namespace: flux-system
data:
  irsa_aws_load_balancer: arn:aws:iam::609897127049:role/haarchri-spaces-01-aws-loadbalancer-controller
  irsa_external_dns: arn:aws:iam::609897127049:role/haarchri-spaces-01-external-dns
  irsa_flux_kustomize: arn:aws:iam::609897127049:role/haarchri-spaces-01-flux-kustomize-controller
  dns_route53: upboundrocks.cloud
  cluster_name: haarchri-spaces-01
  cluster_region: eu-central-1
  external_dns_version: "6.5.6"
  cert_manager_version: "v1.12.3"
  uxp_version: v1.13.2-up.1
  uxp_provider_helm_version: "v0.15.0"
  uxp_provider_kubernetes_version: "v0.9.0"
  spaces_version: "1.0.0"
  spaces_dns_host: haarchri-spaces.upboundrocks.cloud
  spaces_upbound_account: upbound
