apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 5m
  releaseName: external-dns
  targetNamespace: external-dns
  install:
    createNamespace: true
  timeout: 3m
  chart:
    spec:
      chart: external-dns
      version: 6.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 1
    provider: aws
    domainFilters: ["upboundrocks.cloud"]
    policy: sync
    source: ingress
    registry: txt
    txtOwnerId: external-dns
    aws:
      batchChangeSize: 2
      zoneType: public
      region: eu-central-1
    rbac:
      create: true
    serviceAccount:
      create: true
      name: external-dns
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::609897127049:role/haarchri-spaces-01-external-dns
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
    replicas: 2
    podDisruptionBudget:
      minAvailable: 1
