apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: upbound-spaces
  namespace: flux-system
spec:
  releaseName: spaces
  targetNamespace: upbound-system
  interval: 10m
  timeout: 8m
  chart:
    spec:
      chart: spaces
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: upbound-spaces
        namespace: flux-system
  values:
    ingress:
      host: haarchri-spaces.upboundrocks.cloud
    clusterType: eks
    account: upbound
